version: "3.0"
services:
  postgres:
    image: "postgres:latest"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5444:5432"
